name: wilddog_sync
description: Wilddog Sync plugin for Flutter.
version: 0.0.1
author: Hekaiyou <hekaiyou@qq.com>
homepage: https://github.com/ChinaFlutterPioneerTeam/wilddog_sync

flutter:
  plugin:
    androidPackage: com.hekaiyou.wilddogsync
    pluginClass: WilddogSyncPlugin

dependencies:
  flutter:
    sdk: flutter
